export default function Head() {
  return (
    <>
      <title>Jikmunn Blogs App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        href="https://fonts.googleapis.com/css2?family=Sofia+Sans:ital,wght@1,600&display=swap"
        rel="stylesheet"
      />
    </>
  );
}
