import Head from 'next/head';

const HomePage = () => {
  return (
    <div>
      <Head>
        <title>Jikmunn Blogs App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Sofia+Sans:ital,wght@1,600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <h1 className="text-3xl font-bold underline">Hello world!</h1>
    </div>
  );
};

export default HomePage;
