import Head from 'next/head';

//  internal import
import Blogs from '@/components/Blogs/Blogs';

const HomePage = ({ blogs }) => {
  return (
    <div>
      <Head>
        <title>Jikmunn Blogs App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />{' '}
        <link
          href="https://fonts.googleapis.com/css2?family=Sofia+Sans:ital,wght@1,600&display=swap"
          rel="stylesheet"
        />
      </Head>
      {blogs?.map((blog, idx) => (
        <Blogs key={idx} blog={blog} />
      ))}
    </div>
  );
};

export default HomePage;

export const getStaticProps = async () => {
  const res = await fetch('http://localhost:3000/api/blogs');
  const responseData = await res.json();
  const blogs = await responseData?.data;
  return {
    props: { blogs },
  };
};
